on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    env:
      ENABLE_REPO_SYNC: ${{ vars.ENABLE_REPO_SYNC }}
    steps:
      - name: Check if repo sync is enabled
        if: env.ENABLE_REPO_SYNC != 'true'
        run: |
          echo "Repo sync is disabled. Skipping job."
          exit 0
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: repo-sync
      uses: nonameentername/github-sync@v1
      with:
        source_repo: "https://github.com/csound/csound.git"
        source_branch: "*"
        destination_branch: "*"
        sync_tags: "true"
        sync_prs: "true"
        github_token: ${{ secrets.PAT }}
